
package Vista;

/*Importaciones*/
import Controlador.EstadoCivilControlador;
import Controlador.FuncionarioControlador;
import Controlador.TipoIdentificacionControlador;
import DAO.EstadoCivilDAO;
import DAO.EstadoCivilDAOImpl;
import DAO.FuncionarioDAO;
import DAO.FuncionarioDAOImpl;
import DAO.TipoIdentificacionDAO;
import DAO.TipoIdentificacionDAOImpl;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import Modelos.EstadoCivil;
import Modelos.Funcionario;
import Modelos.TipoIdentificacion;
import Utils.Mensajes;
/**
 *
 * @author HOME
 */
public class FuncionariosIUinterface extends javax.swing.JFrame {
    
    //Se definen las Variables
    private TipoIdentificacionControlador tipoIDCtrl;
    private EstadoCivilControlador estadosCivilesCtrl;
    private FuncionarioControlador funcionarioCtrl;

    /**
     * Creates new form Funcionarios
     */
    public FuncionariosIUinterface() {
        initComponents();
        init();

    }
    
    
    public void init() {
        llenarSelectorTipoId();
        llenarSelectorEstadoCivil();
        llenarTablaFuncionarios();
        cambiarEstadoBotones(false);

    }
    
    public void llenarSelectorTipoId() {
        TipoIdentificacionDAO tipoIdentificacionDao = new TipoIdentificacionDAOImpl();
        tipoIDCtrl = new TipoIdentificacionControlador(tipoIdentificacionDao);
        JCBTiposID.setModel(tipoIDCtrl.llenarSelector());
    }
    
    public void llenarSelectorEstadoCivil() {
        EstadoCivilDAO estadoCivilDao = new EstadoCivilDAOImpl();
        estadosCivilesCtrl = new EstadoCivilControlador(estadoCivilDao);
        JCBEstadoCivil.setModel(estadosCivilesCtrl.llenarSelector());
    }
    
    public void llenarTablaFuncionarios() {
        FuncionarioDAO funcionarioDao = new FuncionarioDAOImpl();
        funcionarioCtrl = new FuncionarioControlador(funcionarioDao);
        JTListaFuncionarios.setModel(funcionarioCtrl.llenarTabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGSelectorSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFNumeroDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JRBSexoM = new javax.swing.JRadioButton();
        JRBSexoF = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JCBEstadoCivil = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JDCFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTADireccion = new javax.swing.JTextArea();
        JBGuardar = new javax.swing.JButton();
        JBGuardarCambios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTListaFuncionarios = new javax.swing.JTable();
        JBSalir = new javax.swing.JButton();
        JBEditar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBRefrescar = new javax.swing.JButton();
        JCBTiposID = new javax.swing.JComboBox<>();
        JFTFTelefono = new javax.swing.JFormattedTextField();
        JBCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("TipoID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("FUNCIONARIOS IUD");

        jLabel3.setText("Documento:");

        JTFNumeroDocumento.setName("Documento"); // NOI18N
        JTFNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroDocumentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombres:");

        JTFNombres.setName("nombres"); // NOI18N

        jLabel5.setText("Apellidos:");

        JTFApellidos.setName("Apellidos"); // NOI18N

        jLabel6.setText("Sexo:");

        BGSelectorSexo.add(JRBSexoM);
        JRBSexoM.setText("M");
        JRBSexoM.setName("SexoM"); // NOI18N

        BGSelectorSexo.add(JRBSexoF);
        JRBSexoF.setText("F");
        JRBSexoF.setName("SexoF"); // NOI18N

        jLabel7.setText("Teléfono:");

        jLabel8.setText("Estado Civil:");

        JCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBEstadoCivil.setName("Estado Civil"); // NOI18N

        jLabel9.setText("Fecha Nac.: ");

        JTADireccion.setColumns(20);
        JTADireccion.setRows(5);
        jScrollPane1.setViewportView(JTADireccion);

        JBGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBGuardar.setForeground(new java.awt.Color(0, 0, 0));
        JBGuardar.setText("Guardar");
        JBGuardar.setBorder(null);
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JBGuardarCambios.setBackground(new java.awt.Color(0, 0, 0));
        JBGuardarCambios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBGuardarCambios.setForeground(new java.awt.Color(0, 0, 0));
        JBGuardarCambios.setText("Guardar Cambios");
        JBGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarCambiosActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(0, 102, 102));

        JTListaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTListaFuncionarios.setName("Tabla Funcionarios"); // NOI18N
        JTListaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTListaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTListaFuncionarios);

        JBSalir.setBackground(new java.awt.Color(0, 0, 0));
        JBSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBSalir.setForeground(new java.awt.Color(255, 255, 255));
        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        JBEditar.setBackground(new java.awt.Color(102, 255, 102));
        JBEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBEditar.setForeground(new java.awt.Color(0, 0, 0));
        JBEditar.setText("Editar");
        JBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarActionPerformed(evt);
            }
        });

        JBEliminar.setBackground(new java.awt.Color(0, 0, 0));
        JBEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBEliminar.setForeground(new java.awt.Color(0, 0, 0));
        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        JBRefrescar.setBackground(new java.awt.Color(0, 0, 0));
        JBRefrescar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        JBRefrescar.setText("Refrescar");
        JBRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRefrescarActionPerformed(evt);
            }
        });

        JCBTiposID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBTiposID.setName("TipoID"); // NOI18N

        try {
            JFTFTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFTFTelefono.setName("Telefono"); // NOI18N
        JFTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFTFTelefonoActionPerformed(evt);
            }
        });

        JBCancelar.setBackground(new java.awt.Color(0, 0, 0));
        JBCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JBCancelar.setForeground(new java.awt.Color(0, 0, 0));
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel12.setText("Dirección:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(72, 72, 72)
                                        .addComponent(JRBSexoM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JRBSexoF)
                                        .addGap(146, 146, 146))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(JDCFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel5))
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(JTFApellidos)
                                                    .addComponent(JCBTiposID, 0, 144, Short.MAX_VALUE))
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel8))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTFNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JBGuardarCambios)
                                        .addGap(61, 61, 61)
                                        .addComponent(JBCancelar)))
                                .addGap(0, 63, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JBEliminar)
                                .addGap(45, 45, 45)
                                .addComponent(JBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JFTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JCBTiposID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTFNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JRBSexoM)
                    .addComponent(JRBSexoF)
                    .addComponent(jLabel7)
                    .addComponent(JFTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(JDCFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        // TODO add your handling code here:
        cambiarEstadoBotones(false);
        limpiarCampos();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JFTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFTFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFTFTelefonoActionPerformed

    private void JBRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRefrescarActionPerformed
        // TODO add your handling code here:
        init();
        limpiarCampos();
    }//GEN-LAST:event_JBRefrescarActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarActionPerformed
        // TODO add your handling code here:
        JBGuardar.setEnabled(false);
        JBGuardarCambios.setEnabled(true);
        JBCancelar.setEnabled(true);
        editar();
    }//GEN-LAST:event_JBEditarActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        // TODO add your handling code here:
        if (Mensajes.mensajeConfirm("¿Seguro que deseas salir?", "Salir De la Aplicación")) {
            this.dispose();
        }
    }//GEN-LAST:event_JBSalirActionPerformed

    private void JTListaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTListaFuncionariosMouseClicked
        // TODO add your handling code here:
        if (JTListaFuncionarios.getSelectedRow() != -1) {
            JBEditar.setEnabled(true);
            JBEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_JTListaFuncionariosMouseClicked

    private void JBGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarCambiosActionPerformed
        // TODO add your handling code here:
        if (Mensajes.mensajeConfirm("¿Deseas guardar los cambios?", "Editar")) {
            if (guardarCambios()) {
                Mensajes.mostrarMensaje("Actualización Exitosa", "Edición", JOptionPane.INFORMATION_MESSAGE);
                llenarTablaFuncionarios();
                limpiarCampos();
                cambiarEstadoBotones(false);
            }
        }
    }//GEN-LAST:event_JBGuardarCambiosActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        // TODO add your handling code here:
        if (guardar()) {
            Mensajes.mostrarMensaje("Guardado Exitosamente", "Guardar", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            llenarTablaFuncionarios();
        };
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void JTFNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroDocumentoActionPerformed
    
    public void cambiarEstadoBotones(boolean estado) {
        JBGuardarCambios.setEnabled(estado);
        JBEditar.setEnabled(estado);
        JBEliminar.setEnabled(estado);
        JBCancelar.setEnabled(estado);
        JBGuardar.setEnabled(!estado);
    }
    
    public boolean guardarCambios() {
        int result;
        Funcionario funcionario = new Funcionario();
        
        funcionario.setTipoIdentificacionId(new TipoIdentificacion(JCBTiposID.getSelectedIndex() + 1));
        funcionario.setEstadoCivilId(new EstadoCivil(JCBEstadoCivil.getSelectedIndex() + 1));
        funcionario.setDireccion(JTADireccion.getText().trim().toLowerCase());
        funcionario.setSexo(getSelectedButton());
        funcionario.setNombres(JTFNombres.getText().trim().toUpperCase());
        funcionario.setApellidos(JTFApellidos.getText().trim().toUpperCase());
        funcionario.setNumeroIdentificacion(JTFNumeroDocumento.getText().trim().toUpperCase());
        funcionario.setTelefono(JFTFTelefono.getText());
        if (JDCFechaNacimiento.getDate() != null) {
            funcionario.setFechaNacimiento(JDCFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        } else {
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }
        if (comprobarDatosRequired()) {
            Mensajes.mostrarMensaje("Debes Completar los Campos Obligatorios", "Advertencia", JOptionPane.WARNING_MESSAGE);
            result = 0;
        } else {
            result = funcionarioCtrl.editar(funcionario);
        }
        return result > 0;
    }
    
    public void editar() {
        String documento = (String) JTListaFuncionarios.getValueAt(JTListaFuncionarios.getSelectedRow(), 2);
        Funcionario funcionario = funcionarioCtrl.buscarFuncionario(documento);
        JTADireccion.setText(funcionario.getDireccion());
        if (funcionario.getSexo().equals("F")) {
            JRBSexoF.setSelected(true);
        } else {
            JRBSexoM.setSelected(true);
        }
        JTFNombres.setText(funcionario.getNombres());
        JTFApellidos.setText(funcionario.getApellidos());
        JTFNumeroDocumento.setText(funcionario.getNumeroIdentificacion());
        JFTFTelefono.setText(funcionario.getTelefono());
        JDCFechaNacimiento.setDate(Date.from(funcionario.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        JCBEstadoCivil.setSelectedIndex(funcionario.getEstadoCivilId().getId() - 1);
        JCBTiposID.setSelectedIndex(funcionario.getTipoIdentificacionId().getId() - 1);
        
    }
    
    public void eliminar() {
        String documento = (String) JTListaFuncionarios.getValueAt(JTListaFuncionarios.getSelectedRow(), 2);
        if (Mensajes.mensajeConfirm("¿Deseas Eliminar el Funcionario?", "Eliminar")) {
            funcionarioCtrl.eliminar(documento);
            llenarTablaFuncionarios();
        }
        
    }
    
    public boolean guardar() {
        int result;
        Funcionario funcionario = new Funcionario();
        
        funcionario.setTipoIdentificacionId(new TipoIdentificacion(JCBTiposID.getSelectedIndex() + 1));
        funcionario.setEstadoCivilId(new EstadoCivil(JCBEstadoCivil.getSelectedIndex() + 1));
        funcionario.setDireccion(JTADireccion.getText().trim().toLowerCase());
        funcionario.setSexo(getSelectedButton());
        funcionario.setNombres(JTFNombres.getText().trim().toUpperCase());
        funcionario.setApellidos(JTFApellidos.getText().trim().toUpperCase());
        funcionario.setNumeroIdentificacion(JTFNumeroDocumento.getText().trim().toUpperCase());
        if (JFTFTelefono.isEditValid()) {
            funcionario.setTelefono(JFTFTelefono.getText());
        } else {
            funcionario.setTelefono("000-000-00-00");
        }
        
        if (JDCFechaNacimiento.getDate() != null) {
            funcionario.setFechaNacimiento(JDCFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        } else {
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }
        if (comprobarDatosRequired()) {
            Mensajes.mostrarMensaje("DebeS Completar los Campos Obligatorios", "Advertencia", JOptionPane.WARNING_MESSAGE);
            result = 0;
        } else {
            result = funcionarioCtrl.guardar(funcionario);
        }
        
        return result > 0;
    }
    
    public boolean comprobarDatosRequired() {
        return JTFNumeroDocumento.getText().isBlank() || JTFNombres.getText().isBlank()
                || JTFApellidos.getText().isBlank() || JTADireccion.getText().isBlank();
    }
    
    public void limpiarCampos() {
        JTADireccion.setText("");
        JRBSexoF.setSelected(false);
        JRBSexoM.setSelected(false);
        JTFNombres.setText("");
        JTFApellidos.setText("");
        JTFNumeroDocumento.setText("");
        JFTFTelefono.setText("");
        JDCFechaNacimiento.setDate(null);
        JCBEstadoCivil.setSelectedIndex(0);
        JCBTiposID.setSelectedIndex(0);
    }
    
    public String getSelectedButton() {
        Enumeration<AbstractButton> buttons = BGSelectorSexo.getElements();
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionariosIUinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionariosIUinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionariosIUinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosIUinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionariosIUinterface().setVisible(true);
            }
        });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGSelectorSexo;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBEditar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBGuardarCambios;
    private javax.swing.JButton JBRefrescar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JComboBox<String> JCBEstadoCivil;
    private javax.swing.JComboBox<String> JCBTiposID;
    private com.toedter.calendar.JDateChooser JDCFechaNacimiento;
    private javax.swing.JFormattedTextField JFTFTelefono;
    private javax.swing.JRadioButton JRBSexoF;
    private javax.swing.JRadioButton JRBSexoM;
    private javax.swing.JTextArea JTADireccion;
    private javax.swing.JTextField JTFApellidos;
    private javax.swing.JTextField JTFNombres;
    private javax.swing.JTextField JTFNumeroDocumento;
    private javax.swing.JTable JTListaFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}



